on:
  workflow_dispatch: # Manually running a workflow
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
name: Linux build
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #python-version: [ 3.7, 3.8, 3.9 ]
        python-version: [ 3.12 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip packages
        uses: actions/cache@v4
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}-torch-cython
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-
      - name: Cache huggingface models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-huggingface-
      - name: Install torch and Cython
        run: |
          python -m pip install --upgrade pip
          pip install Cython torch
      - name: Install from pypi
        run: |
          pip install -U webresearcher
          python -c "import webresearcher; print(webresearcher.__version__)"
          pip uninstall -y webresearcher
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .
          pip install pytest pytest-cov black flake8 mypy
      - name: PKG-TEST
        run: |
          python -m pytest